services:
  db:
    image: postgres:18@sha256:b6b4d0b75c699a2c94dfc5a94fe09f38630f3b67ab0e1653ede1b7ac8e13c197
    environment:
      POSTGRES_PASSWORD: ${DATABASE_SUPERUSER_PASSWORD}
      DATABASE_ORM_PASSWORD: ${DATABASE_ORM_PASSWORD}
      DATABASE_ORM_USERNAME: ${DATABASE_ORM_USERNAME}
      DATABASE_APP_PASSWORD: ${DATABASE_APP_PASSWORD}
      DATABASE_APP_USERNAME: ${DATABASE_APP_USERNAME}
      DATABASE_NAME: ${DATABASE_NAME}
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  prisma:
    build:
      context: ./api/
      dockerfile: Dockerfile.prisma
    depends_on:
      db:
        condition: service_healthy
    restart: no
    environment:
      DATABASE_URL: "postgresql://${DATABASE_ORM_USERNAME}:${DATABASE_ORM_PASSWORD}@db:5432/${DATABASE_NAME}?schema=appschema"
    networks:
      - internal

  api:
    build:
      context: ./api/
      dockerfile: Dockerfile.api
      target: runner
    depends_on:
      db:
        condition: service_healthy
      prisma:
        condition: service_completed_successfully
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgresql://${DATABASE_APP_USERNAME}:${DATABASE_APP_PASSWORD}@db:5432/${DATABASE_NAME}?schema=appschema"
      API_BEARER_TOKEN: ${API_BEARER_TOKEN}
      LINK_PROTOCOL: ${LINK_PROTOCOL}
      LINK_HOSTNAME: ${LINK_HOSTNAME}
      LINK_PORT: ${LINK_PORT}
    networks:
      - internal

  app:
    build:
      context: ./app/
      dockerfile: Dockerfile
      target: runner
    depends_on:
      db:
        condition: service_healthy
      api:
        condition: service_healthy
    expose:
      - ${DOCKER_APP_PORT}
    restart: unless-stopped
    environment:
      DOCKER_API_HOSTNAME: api
      DOCKER_API_PORT: 3000
    labels:
      - traefik.enable=true
      - traefik.http.routers.${DOCKER_APP_TRAEFIK_NAME_HTTP}.rule=Host(`${LINK_HOSTNAME}`)
      - traefik.http.routers.${DOCKER_APP_TRAEFIK_NAME_HTTP}.entrypoints=web
      - traefik.http.services.${DOCKER_APP_TRAEFIK_NAME_HTTP}.loadbalancer.server.port=${DOCKER_APP_PORT}
      - traefik.http.routers.${DOCKER_APP_TRAEFIK_NAME_HTTP}.service=${DOCKER_APP_TRAEFIK_NAME_HTTP}
      - traefik.http.routers.${DOCKER_APP_TRAEFIK_NAME_HTTP}.middlewares=redirect-to-https@file
      - traefik.http.routers.${DOCKER_APP_TRAEFIK_NAME_HTTPS}.rule=Host(`${LINK_HOSTNAME}`)
      - traefik.http.routers.${DOCKER_APP_TRAEFIK_NAME_HTTPS}.entrypoints=websecure
      - traefik.http.services.${DOCKER_APP_TRAEFIK_NAME_HTTPS}.loadbalancer.server.port=${DOCKER_APP_PORT}
      - traefik.http.routers.${DOCKER_APP_TRAEFIK_NAME_HTTPS}.service=${DOCKER_APP_TRAEFIK_NAME_HTTPS}
      - traefik.http.routers.${DOCKER_APP_TRAEFIK_NAME_HTTPS}.tls.certresolver=letsencrypt
    networks:
      - dokploy-network
      - internal

  admin:
    build:
      context: ./admin/
      dockerfile: Dockerfile
      target: runner
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      api:
        condition: service_healthy
    expose:
      - ${DOCKER_ADMIN_PORT}
    environment:
      API_BEARER_TOKEN: ${API_BEARER_TOKEN}
      DOCKER_API_HOSTNAME: api
      DOCKER_API_PORT: 3000
    labels:
      - traefik.enable=true
      - traefik.http.routers.${DOCKER_ADMIN_TRAEFIK_NAME_HTTP}.rule=Host(`${ADMIN_HOSTNAME}`)
      - traefik.http.routers.${DOCKER_ADMIN_TRAEFIK_NAME_HTTP}.entrypoints=web
      - traefik.http.services.${DOCKER_ADMIN_TRAEFIK_NAME_HTTP}.loadbalancer.server.port=${DOCKER_ADMIN_PORT}
      - traefik.http.routers.${DOCKER_ADMIN_TRAEFIK_NAME_HTTP}.service=${DOCKER_ADMIN_TRAEFIK_NAME_HTTP}
      - traefik.http.routers.${DOCKER_ADMIN_TRAEFIK_NAME_HTTP}.middlewares=redirect-to-https@file
      - traefik.http.routers.${DOCKER_ADMIN_TRAEFIK_NAME_HTTPS}.rule=Host(`${ADMIN_HOSTNAME}`)
      - traefik.http.routers.${DOCKER_ADMIN_TRAEFIK_NAME_HTTPS}.entrypoints=websecure
      - traefik.http.services.${DOCKER_ADMIN_TRAEFIK_NAME_HTTPS}.loadbalancer.server.port=${DOCKER_ADMIN_PORT}
      - traefik.http.routers.${DOCKER_ADMIN_TRAEFIK_NAME_HTTPS}.service=${DOCKER_ADMIN_TRAEFIK_NAME_HTTPS}
      - traefik.http.routers.${DOCKER_ADMIN_TRAEFIK_NAME_HTTPS}.tls.certresolver=letsencrypt
      - traefik.http.middlewares.${DOCKER_ADMIN_TRAEFIK_NAME_MIDDLEWARE}.basicauth.users=${ADMIN_BASIC_AUTH}
      - traefik.http.middlewares.${DOCKER_ADMIN_TRAEFIK_NAME_MIDDLEWARE}.basicauth.realm=${DOCKER_ADMIN_TRAEFIK_NAME_REALM}
      - traefik.http.routers.${DOCKER_ADMIN_TRAEFIK_NAME_HTTPS}.middlewares=${DOCKER_ADMIN_TRAEFIK_NAME_MIDDLEWARE}
    networks:
      - dokploy-network
      - internal

volumes:
  db-data:

networks:
  internal:
    driver: bridge
    internal: true
  dokploy-network:
    external: true
