services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      PGPORT: 5432
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}
      interval: 10s
      timeout: 5s
      retries: 5

  prisma:
    build:
      context: ./api/
      dockerfile: Dockerfile.prisma
    depends_on:
      db:
        condition: service_healthy
    restart: no
    environment:
      DATABASE_URL: "postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}"

  api:
    build:
      context: ./api/
      dockerfile: Dockerfile.api
      target: runner
    depends_on:
      db:
        condition: service_healthy
      prisma:
        condition: service_completed_successfully
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}"
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      LINK_PROTOCOL: ${LINK_PROTOCOL}
      LINK_HOSTNAME: ${LINK_HOSTNAME}
      LINK_PORT: ${LINK_PORT}

  app:
    build:
      context: ./app/
      dockerfile: Dockerfile
      target: runner
    depends_on:
      db:
        condition: service_healthy
      api:
        condition: service_healthy
    ports:
      - "${DOCKER_APP_PORT:-3001}:3001"
    restart: unless-stopped
    environment:
      - DOCKER_API_HOSTNAME=api
      - DOCKER_API_PORT=3000

volumes:
  db-data:
