FROM node:22-slim

RUN apt-get update -y

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

RUN npm ci

COPY ./prisma ./prisma
COPY prisma.config.ts ./

CMD ["sh", "-c", "npx prisma migrate deploy"]

